### ISSUE TITLE
High-Quality Hero Image and Engaging Descriptions

### ISSUE THREAD

**Issue by Ronan525** [Ronan525/personal-project#2]
### User Story

_As a Site User, I want to understand the purpose of the website immediately upon arrival so that I can get a visual understanding of the services offered._

### Acceptance Criteria

- [x] A hero section is present at the top of the homepage.
- [x] The hero section includes a welcoming headline and a brief description of the website.

### Tasks

- [x] Create a responsive navigation bar that includes links to the Home and Lists pages.
- [x] Implement a collapsible menu for mobile devices.
- [x] Add a footer that includes social media links and copyright information.
